DROP TABLE IF EXISTS TOP_CATEGORY;
CREATE TABLE TOP_CATEGORY
(
	TOP_ID INTEGER NOT NULL AUTO_INCREMENT,
	TOP_NAME VARCHAR(255) NOT NULL,
	CREATOR VARCHAR(255) NOT NULL,
	CREATE_DTTM VARCHAR(255) NOT NULL,
	UPDATER VARCHAR(255) NOT NULL,
	UPDATE_DTTM VARCHAR(255) NOT NULL,
	PRIMARY KEY(TOP_ID)
);

DROP TABLE IF EXISTS MIDDLE_CATEGORY;
CREATE TABLE MIDDLE_CATEGORY
(
	MIDDLE_ID INTEGER NOT NULL AUTO_INCREMENT,
	MIDDLE_NAME VARCHAR(255) NOT NULL,
	TOP_ID INTEGER NOT NULL,
	CREATOR VARCHAR(255) NOT NULL,
	CREATE_DTTM VARCHAR(255) NOT NULL,
	UPDATER VARCHAR(255) NOT NULL,
	UPDATE_DTTM VARCHAR(255) NOT NULL,
	PRIMARY KEY(MIDDLE_ID)
);

DROP TABLE IF EXISTS BOTTOM_CATEGORY;
CREATE TABLE BOTTOM_CATEGORY
(
	BOTTOM_ID INTEGER NOT NULL AUTO_INCREMENT,
	BOTTOM_NAME VARCHAR(255) NOT NULL,
	MIDDLE_ID INTEGER NOT NULL,
	BRAND_ID INTEGER NOT NULL,
	BEST_ITEM BOOLEAN,
	CREATOR VARCHAR(255) NOT NULL,
	CREATE_DTTM VARCHAR(255) NOT NULL,
	UPDATER VARCHAR(255) NOT NULL,
	UPDATE_DTTM VARCHAR(255) NOT NULL,
	PRIMARY KEY(BOTTOM_ID)
);

DROP TABLE IF EXISTS BRAND_CODE_MST;
CREATE TABLE BRAND_CODE_MST
(
	BRAND_ID INTEGER NOT NULL AUTO_INCREMENT,
	BRAND_NAME VARCHAR(255) NOT NULL,
	CREATOR VARCHAR(255) NOT NULL,
	CREATE_DTTM VARCHAR(255) NOT NULL,
	UPDATER VARCHAR(255) NOT NULL,
	UPDATE_DTTM VARCHAR(255) NOT NULL,
	PRIMARY KEY(BRAND_ID)
);